steps:
  # Step 1: Check/create Artifact Registry repository
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if ! gcloud artifacts repositories describe vamsi-artifact-cloudrun --location=asia-east1 --project=enhub-cloud-interns; then
          echo "Repository doesn't exist. Creating now."
          gcloud artifacts repositories create vamsi-artifact-cloudrun \
            --repository-format=docker \
            --location=asia-east1 \
            --project=enhub-cloud-interns
        else
          echo "Repository already exists."
        fi

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'asia-east1-docker.pkg.dev/enhub-cloud-interns/vamsi-artifact-cloudrun/vamsi-image:latest',
      '.'
    ]

  # Step 3: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'asia-east1-docker.pkg.dev/enhub-cloud-interns/vamsi-artifact-cloudrun/vamsi-image:latest'
    ]

  # Step 4: Create a release for the build image
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'deploy', 'releases', 'create', 'vamsi-release-${BUILD_ID}',
      '--project=enhub-cloud-interns',
      '--region=asia-east1',
      '--delivery-pipeline=vamsi-pipeline',
      '--images=vamsi-image=asia-east1-docker.pkg.dev/enhub-cloud-interns/vamsi-artifact-cloudrun/vamsi-image:latest'
    ]
    id: create-release
    waitFor: ['-']  # Ensures this step runs after all previous steps.

  # Step 5: Promote the release to the 'prod' target
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'deploy', 'releases', 'promote', 'vamsi-release-${BUILD_ID}',
      '--project=enhub-cloud-interns',
      '--region=asia-east1'
    ]
    waitFor: ['create-release']  # Now references the correct step ID.

images:
  - 'asia-east1-docker.pkg.dev/enhub-cloud-interns/vamsi-artifact-cloudrun/vamsi-image:latest'

options:
  logging: CLOUD_LOGGING_ONLY
