steps:
  # Step 1: Ensure Artifact Registry exists
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if ! gcloud artifacts repositories describe vamsi-artifact-cloudrun --location=asia-east1 --project=enhub-cloud-interns; then
          echo "Repository doesn't exist. Creating now."
          gcloud artifacts repositories create vamsi-artifact-cloudrun \
            --repository-format=docker \
            --location=asia-east1 \
            --project=enhub-cloud-interns
        else
          echo "Repository already exists."
        fi

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-east1-docker.pkg.dev/enhub-cloud-interns/vamsi-artifact-cloudrun/vamsi-image:latest',
        '.'
      ]

  # Step 3: Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-east1-docker.pkg.dev/enhub-cloud-interns/vamsi-artifact-cloudrun/vamsi-image:latest'
      ]

  # Step 4: Apply Cloud Deploy pipeline and target config
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'deploy', 'apply',
        '--file=clouddeploy.yaml',
        '--region=asia-east1',
        '--project=enhub-cloud-interns'
      ]
    id: apply-deploy-config

  # Step 5: Create a unique release using timestamp
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        RELEASE_NAME="vamsi-release-$(date +%s)"
        echo "Creating release: $RELEASE_NAME"
        gcloud deploy releases create "$RELEASE_NAME" \
          --project=enhub-cloud-interns \
          --region=asia-east1 \
          --delivery-pipeline=vamsi-pipeline \
          --images=vamsi-image=asia-east1-docker.pkg.dev/enhub-cloud-interns/vamsi-artifact-cloudrun/vamsi-image:latest
        echo "$RELEASE_NAME" > /workspace/release-name.txt
    id: create-release
    waitFor: ['apply-deploy-config']

  # Step 6: Promote the release
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        RELEASE_NAME=$(cat /workspace/release-name.txt)
        echo "Promoting release: $RELEASE_NAME"
        gcloud deploy rollouts approve \
          --release="$RELEASE_NAME" \
          --region=asia-east1 \
          --project=enhub-cloud-interns
    waitFor: ['create-release']

images:
  - 'asia-east1-docker.pkg.dev/enhub-cloud-interns/vamsi-artifact-cloudrun/vamsi-image:latest'

options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: 1064351983714-compute@developer.gserviceaccount.com
